[package]
name = "kam-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "kam-agent"
path = "src/main.rs"

[dependencies]
kam-canary = { workspace = true }
kam-core = { workspace = true }
kam-ipc = { workspace = true }
kam-firewall = { workspace = true }
kam-quarantine = { workspace = true }
kam-scanner = { workspace = true }
kam-schedule = { workspace = true }
kam-storage = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
windows-service = "0.8.1"

[lints]
workspace = true
